baseURL: "https://scifuentes14.github.io/" 
title: Sebastian Cifuentes
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 4
        - name: Papers
          url: papers/
          weight: 3
        - name: Courses
          url: courses/
          weight: 4

params:
    description: "This website hosts Sebastian Cifuentes' research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Sebastian Cifuentes
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","courses","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sebastian Cifuentes
          subtitle: "I am a Finance Ph.D. candidate at the Rady School of Management, University of California, San Diego. My research interests focus on entrepreneurship, housing markets, and economic inequality. I obtained an M.Sc. in Finance and an Industrial Engineering degree with a major in Mining Engineering from the Pontificia Universidad Católica de Chile."
          imageUrl: "WebPage_Photo.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
    socialIcons:
        - name: CV
          url: NewCV_SC.pdf
        - name: Email
          url: mailto:scifuentes@ucsd.edu
        - name: Location
          url: location/
        - name: Twitter
          url: https://x.com/scifuentes14

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Sebastian Cifuentes"
      icon: favicon-32x32.png
      iconHeight: 20

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
